export const Data = [
  { "State": "Uttar Pradesh", "Region": "East", "Crop": "Rice", "Duration": "3 months", "Varieties": "Aus", "SownMonth": "April" },
  { "State": "West Bengal", "Region": "East", "Crop": "Rice", "Duration": "4-5 months", "Varieties": "Aman", "SownMonth": "June" },
  { "State": "Assam", "Region": "East", "Crop": "Rice", "Duration": "4-5 months", "Varieties": "Aman", "SownMonth": "June" },
  { "State": "Bihar", "Region": "East", "Crop": "Rice", "Duration": "4-5 months", "Varieties": "Aman", "SownMonth": "June" },
  { "State": "Jharkhand", "Region": "East", "Crop": "Rice", "Duration": "4-5 months", "Varieties": "Aman", "SownMonth": "June" },
  { "State": "Odisha", "Region": "East", "Crop": "Rice", "Duration": "4-5 months", "Varieties": "Aman", "SownMonth": "June" },
  { "State": "West Bengal", "Region": "East", "Crop": "Rice", "Duration": "6 months", "Varieties": "Boro", "SownMonth": "November" },
  { "State": "Assam", "Region": "East", "Crop": "Rice", "Duration": "6 months", "Varieties": "Boro", "SownMonth": "November" },
  { "State": "Bihar", "Region": "East", "Crop": "Rice", "Duration": "6 months", "Varieties": "Boro", "SownMonth": "November" },
  { "State": "Jharkhand", "Region": "East", "Crop": "Rice", "Duration": "6 months", "Varieties": "Boro", "SownMonth": "November" },
  { "State": "Odisha", "Region": "East", "Crop": "Rice", "Duration": "6 months", "Varieties": "Boro", "SownMonth": "November" },
  { "State": "Uttar Pradesh", "Region": "Central", "Crop": "Wheat", "Duration": "4-5 months", "Varieties": "VL-832", "SownMonth": "November" },
  { "State": "Bihar", "Region": "Central", "Crop": "Wheat", "Duration": "4-5 months", "Varieties": "VL-832", "SownMonth": "November" },
  { "State": "Madhya Pradesh", "Region": "Central", "Crop": "Wheat", "Duration": "4-5 months", "Varieties": "VL-832", "SownMonth": "November" },
  { "State": "Rajasthan", "Region": "Central", "Crop": "Wheat", "Duration": "4-5 months", "Varieties": "VL-832", "SownMonth": "November" },
  { "State": "Rajasthan", "Region": "Central", "Crop": "Pearl millet", "Duration": "NA", "Varieties": "Pearl millet", "SownMonth": "June" },
  { "State": "Maharashtra", "Region": "Central", "Crop": "Pearl millet", "Duration": "NA", "Varieties": "Pearl millet", "SownMonth": "June" },
  { "State": "Gujarat", "Region": "Central", "Crop": "Pearl millet", "Duration": "NA", "Varieties": "Pearl millet", "SownMonth": "June" },
  { "State": "Haryana", "Region": "Central", "Crop": "Pearl millet", "Duration": "NA", "Varieties": "Pearl millet", "SownMonth": "June" },
  { "State": "Uttar Pradesh", "Region": "Central", "Crop": "Pearl millet", "Duration": "NA", "Varieties": "Pearl millet", "SownMonth": "June" },
  { "State": "Madhya Pradesh", "Region": "Central", "Crop": "Pearl millet", "Duration": "NA", "Varieties": "Pearl millet", "SownMonth": "June" },
  { "State": "Karnataka", "Region": "South", "Crop": "Finger millet", "Duration": "NA", "Varieties": "Finger millet", "SownMonth": "June" },
  { "State": "Tamil Nadu", "Region": "South", "Crop": "Finger millet", "Duration": "NA", "Varieties": "Finger millet", "SownMonth": "June" },
  { "State": "Andhra Pradesh", "Region": "South", "Crop": "Finger millet", "Duration": "NA", "Varieties": "Finger millet", "SownMonth": "June" },
  { "State": "Maharashtra", "Region": "Central", "Crop": "Finger millet", "Duration": "NA", "Varieties": "Finger millet", "SownMonth": "June" },
  { "State": "Odisha", "Region": "East", "Crop": "Finger millet", "Duration": "NA", "Varieties": "Finger millet", "SownMonth": "June" },
  { "State": "Uttar Pradesh", "Region": "Central", "Crop": "Foxtail millet", "Duration": "NA", "Varieties": "Foxtail millet", "SownMonth": "July" },
  { "State": "Bihar", "Region": "East", "Crop": "Foxtail millet", "Duration": "NA", "Varieties": "Foxtail millet", "SownMonth": "July" },
  { "State": "Jharkhand", "Region": "East", "Crop": "Foxtail millet", "Duration": "NA", "Varieties": "Foxtail millet", "SownMonth": "July" },
  { "State": "Chhattisgarh", "Region": "Central", "Crop": "Foxtail millet", "Duration": "NA", "Varieties": "Foxtail millet", "SownMonth": "July" },
  { "State": "Odisha", "Region": "East", "Crop": "Foxtail millet", "Duration": "NA", "Varieties": "Foxtail millet", "SownMonth": "July" },
  { "State": "Maharashtra", "Region": "Central", "Crop": "Sorghum", "Duration": "NA", "Varieties": "Sorghum", "SownMonth": "July" },
  { "State": "Karnataka", "Region": "South", "Crop": "Sorghum", "Duration": "NA", "Varieties": "Sorghum", "SownMonth": "July" },
  { "State": "Andhra Pradesh", "Region": "South", "Crop": "Sorghum", "Duration": "NA", "Varieties": "Sorghum", "SownMonth": "July" },
  { "State": "Telangana", "Region": "South", "Crop": "Sorghum", "Duration": "NA", "Varieties": "Sorghum", "SownMonth": "July" },
  { "State": "Tamil Nadu", "Region": "South", "Crop": "Sorghum", "Duration": "NA", "Varieties": "Sorghum", "SownMonth": "July" },
  { "State": "Karnataka", "Region": "South", "Crop": "Maize", "Duration": "3-4 months", "Varieties": "Yellow dent", "SownMonth": "June" },
  { "State": "Andhra Pradesh", "Region": "South", "Crop": "Maize", "Duration": "3-4 months", "Varieties": "Yellow dent", "SownMonth": "June" },
  { "State": "Bihar", "Region": "East", "Crop": "Maize", "Duration": "3-4 months", "Varieties": "Yellow dent", "SownMonth": "June" },
  { "State": "Uttar Pradesh", "Region": "Central", "Crop": "Maize", "Duration": "3-4 months", "Varieties": "Yellow dent", "SownMonth": "June" },
  { "State": "Karnataka", "Region": "South", "Crop": "Maize", "Duration": "3-4 months", "Varieties": "White flint", "SownMonth": "June" },
  { "State": "Andhra Pradesh", "Region": "South", "Crop": "Maize", "Duration": "3-4 months", "Varieties": "White flint", "SownMonth": "June" },
  { "State": "Bihar", "Region": "East", "Crop": "Maize", "Duration": "3-4 months", "Varieties": "White flint", "SownMonth": "June" },
  { "State": "Uttar Pradesh", "Region": "Central", "Crop": "Maize", "Duration": "3-4 months", "Varieties": "White flint", "SownMonth": "June" },
  { "State": "Maharashtra", "Region": "Central", "Crop": "Sorghum", "Duration": "NA", "Varieties": "Sorghum", "SownMonth": "June" },
  { "State": "Karnataka", "Region": "South", "Crop": "Sorghum", "Duration": "NA", "Varieties": "Sorghum", "SownMonth": "June" },
  { "State": "Andhra Pradesh", "Region": "South", "Crop": "Sorghum", "Duration": "NA", "Varieties": "Sorghum", "SownMonth": "June" },
  { "State": "Telangana", "Region": "South", "Crop": "Sorghum", "Duration": "NA", "Varieties": "Sorghum", "SownMonth": "June" },
  { "State": "Tamil Nadu", "Region": "South", "Crop": "Sorghum", "Duration": "NA", "Varieties": "Sorghum", "SownMonth": "June" },
  { "State": "Karnataka", "Region": "South", "Crop": "Maize", "Duration": "3-4 months", "Varieties": "Yellow dent", "SownMonth": "June" },
  { "State": "Andhra Pradesh", "Region": "South", "Crop": "Maize", "Duration": "3-4 months", "Varieties": "Yellow dent", "SownMonth": "June" },
  { "State": "Bihar", "Region": "East", "Crop": "Maize", "Duration": "3-4 months", "Varieties": "Yellow dent", "SownMonth": "June" },
  { "State": "Uttar Pradesh", "Region": "Central", "Crop": "Maize", "Duration": "3-4 months", "Varieties": "Yellow dent", "SownMonth": "June" },
  { "State": "Karnataka", "Region": "South", "Crop": "Maize", "Duration": "3-4 months", "Varieties": "White flint", "SownMonth": "June" },
  { "State": "Andhra Pradesh", "Region": "South", "Crop": "Maize", "Duration": "3-4 months", "Varieties": "White flint", "SownMonth": "June" },
  { "State": "Bihar", "Region": "East", "Crop": "Maize", "Duration": "3-4 months", "Varieties": "White flint", "SownMonth": "June" },
  { "State": "Uttar Pradesh", "Region": "Central", "Crop": "Maize", "Duration": "3-4 months", "Varieties": "White flint", "SownMonth": "June" }
];

export default Data;
